---
- name: Manage mariadb databases
  register: _mariadb_databases
  mysql_db:
    name: "{{ item.name }}"
    collation: "{{ item.collation | default('utf8_general_ci') }}"
    encoding: "{{ item.encoding | default('utf8') }}"
    state: present
    login_user: '{{ _mariadb_login_user }}'
    login_password: '{{ _mariadb_login_password | default(omit) }}'
  no_log: true
  with_items: '{{ mariadb_databases }}'
  when: mariadb_databases|length