---
- name: Purge all mysql packages
  apt:
    pkg: '{{ item }}'
    state: absent
    purge: true
  when: mariadb_not_installed
  with_items:
    - 'mysql*'
    - 'mysql'

- name: Install mariadb keys
  apt_key:
    keyserver: "{{ mariadb_apt_keyserver }}"
    id: "{{ mariadb_apt_keyid }}"
    state: present

- name: Pin mariadb apt repository
  template:
    src: 'mariadb.pref'
    dest: /etc/apt/preferences.d/mariadb.pref
  when: mariadb_pin_repository

- name: Install mariadb apt repositories
  apt_repository:
    repo: "{{ item }}"
    state: present
    update_cache: yes
  register: mariadb_install_packages
  with_items: '{{mariadb_apt_repositories}}'

- name: Install mariadb apt dependencies
  apt:
    pkg: '{{ item }}'
    state: present
    force: yes
  with_items: '{{mariadb_apt_dependencies}}'

# Run when _NOT_ Ubuntu 12
- name: Install mariadb apt dependencies
  apt:
    pkg: '{{ item }}'
    state: build-dep
    force: yes
  with_items: '{{mariadb_apt_packages}}'
  changed_when: false
  when: (ansible_distribution == 'Ubuntu' and ansible_distribution_version|int < 14) == false

- name: Install mariadb server apt packages
  apt:
    pkg: '{{ item }}'
    state: present
    force: yes
  with_items: '{{mariadb_apt_packages}}'

- name: Install mariadb tools
  apt:
    name: '{{ item }}'
    state: present
  with_items: '{{mariadb_apt_tools_packages}}'
  when: mariadb_install_tools

# Stop automatically started mariadb on first run and delete ib_logfile
# in case a custom log file size is defined.
- name: Stop mariadb after inital installation (for cleanup)
  when: mariadb_not_installed
  service:
    name: mysql
    state: stopped
    sleep: 5

- name: Delete default innodb log files
  when: mariadb_not_installed
  file:
    path: '{{ mariadb_datadir }}/ib_logfile[01]'
    state: absent
