---
- name: Remove test database
  mysql_db:
    name: test
    state: absent
    login_user: '{{ _mariadb_login_user }}'
    login_password: '{{ _mariadb_login_password }}'
  no_log: mariadb_debug == false

- name: Fetch all hosts
  command: mysql {{ _mariadb_cmd_login }} -NBe "SELECT Host FROM mysql.user ORDER BY (Host='localhost') ASC"
  register: mysql_hosts
  changed_when: false

- name: Delete all users not in allowed hosts
  shell: mysql {{ _mariadb_cmd_login }} -NBe 'DELETE FROM mysql.user WHERE host = "{{ item }}"'
  when: mariadb_install_packages | bool and item not in mariadb_allowed_hosts
  with_items: '{{ mysql_hosts.stdout_lines }}'

- name: Remove anonymous user
  mysql_user:
    name: ''
    host: "{{ item }}"
    state: absent
    login_user: '{{ _mariadb_login_user }}'
    login_password: '{{ _mariadb_login_password }}'
  no_log: mariadb_debug == false
  with_items: '{{ mysql_hosts.stdout_lines }}'

- name: Add administrative user
  mysql_user:
    user: '{{ mariadb_admin_user }}'
    password: '{{ mariadb_admin_password | default(omit) }}'
    host: '{{ item }}'
    priv: '*.*:ALL,GRANT'
    state: present
    check_implicit_admin: true
    login_user: '{{ _mariadb_login_user }}'
    login_password: '{{ _mariadb_login_password | default(omit) }}'
  no_log: mariadb_debug == false
  changed_when: false # required for idempotence
  with_items: '{{ mariadb_admin_hosts }}'

- name: Copy .my.cnf file with credentials for administrative user
  template:
    src: "user-my.cnf"
    dest: "{{ mariadb_admin_home }}/.my.cnf"
    owner: root
    group: root
    mode: '0600'

- name: Copy .my.cnf file with credentials for normal users
  template:
    src: "user-my.cnf"
    dest: "{{ item.dest }}"
    owner: '{{ item.owner }}'
    group: '{{ item.group }}'
    mode: '0600'
  when: mariadb_credentials_file|length
  with_items: '{{ mariadb_credentials_file }}'

- name: 'Reset login facts'
  set_fact:
    _mariadb_login_user: "{{ mariadb_admin_user }}"
    _mariadb_login_password: "{{ mariadb_admin_password | default(omit) }}"
    _mariadb_cmd_login: '-u "{{ mariadb_admin_user }}" -p"{{ mariadb_admin_password }}"'

- name: 'Reset login facts again'
  set_fact:
    _mariadb_cmd_login: '-u "{{ mariadb_admin_user }}"'
  when: mariadb_admin_password == ''

- name: Remove root user completely
  mysql_user:
    user: 'root'
    host: '{{ item }}'
    state: absent
    login_user: '{{ _mariadb_login_user }}'
    login_password: '{{ _mariadb_login_password | default(omit) }}'
  no_log: mariadb_debug == false
  when: mariadb_admin_user != 'root'
  with_items: '{{ mysql_hosts.stdout_lines }}'
